name: Test Azure Login

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_FLEXCLOUD }}
        client-id: ${{ secrets.AZURE_CLIENT_ID_FLEXCLOUD }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID_FLEXCLOUD }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_FLEXCLOUD }}
